global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.000'] ## Edit with the IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.000:9100'] ## Edit with the IP Address of the localhost
